// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Domain.Protos.Messages {

  /// <summary>Holder for reflection information generated from messages/messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdtZXNzYWdlcy9tZXNzYWdlcy5wcm90bxIIbWVzc2FnZXMaH2dvb2dsZS9w",
            "cm90b2J1Zi90aW1lc3RhbXAucHJvdG8aJm1lc3NhZ2VzL2VsZW1lbnRfY3Jl",
            "YXRlZF9tZXNzYWdlLnByb3RvGiZtZXNzYWdlcy9lbGVtZW50X2RlbGV0ZWRf",
            "bWVzc2FnZS5wcm90byLAAQoHTWVzc2FnZRIyCg50aW1lX2dlbmVyYXRlZBgB",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASOgoPZWxlbWVudF9j",
            "cmVhdGVkGAIgASgLMh8ubWVzc2FnZXMuRWxlbWVudENyZWF0ZWRNZXNzYWdl",
            "SAASOgoPZWxlbWVudF9kZWxldGVkGAMgASgLMh8ubWVzc2FnZXMuRWxlbWVu",
            "dERlbGV0ZWRNZXNzYWdlSABCCQoHbWVzc2FnZUIZqgIWRG9tYWluLlByb3Rv",
            "cy5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Domain.Protos.Messages.ElementCreatedMessageReflection.Descriptor, global::Domain.Protos.Messages.ElementDeletedMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Domain.Protos.Messages.Message), global::Domain.Protos.Messages.Message.Parser, new[]{ "TimeGenerated", "ElementCreated", "ElementDeleted" }, new[]{ "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Base message definition
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Domain.Protos.Messages.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      timeGenerated_ = other.timeGenerated_ != null ? other.timeGenerated_.Clone() : null;
      switch (other.MessageCase) {
        case MessageOneofCase.ElementCreated:
          ElementCreated = other.ElementCreated.Clone();
          break;
        case MessageOneofCase.ElementDeleted:
          ElementDeleted = other.ElementDeleted.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "time_generated" field.</summary>
    public const int TimeGeneratedFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeGenerated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeGenerated {
      get { return timeGenerated_; }
      set {
        timeGenerated_ = value;
      }
    }

    /// <summary>Field number for the "element_created" field.</summary>
    public const int ElementCreatedFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Domain.Protos.Messages.ElementCreatedMessage ElementCreated {
      get { return messageCase_ == MessageOneofCase.ElementCreated ? (global::Domain.Protos.Messages.ElementCreatedMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ElementCreated;
      }
    }

    /// <summary>Field number for the "element_deleted" field.</summary>
    public const int ElementDeletedFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Domain.Protos.Messages.ElementDeletedMessage ElementDeleted {
      get { return messageCase_ == MessageOneofCase.ElementDeleted ? (global::Domain.Protos.Messages.ElementDeletedMessage) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ElementDeleted;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      ElementCreated = 2,
      ElementDeleted = 3,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TimeGenerated, other.TimeGenerated)) return false;
      if (!object.Equals(ElementCreated, other.ElementCreated)) return false;
      if (!object.Equals(ElementDeleted, other.ElementDeleted)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (timeGenerated_ != null) hash ^= TimeGenerated.GetHashCode();
      if (messageCase_ == MessageOneofCase.ElementCreated) hash ^= ElementCreated.GetHashCode();
      if (messageCase_ == MessageOneofCase.ElementDeleted) hash ^= ElementDeleted.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (timeGenerated_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TimeGenerated);
      }
      if (messageCase_ == MessageOneofCase.ElementCreated) {
        output.WriteRawTag(18);
        output.WriteMessage(ElementCreated);
      }
      if (messageCase_ == MessageOneofCase.ElementDeleted) {
        output.WriteRawTag(26);
        output.WriteMessage(ElementDeleted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (timeGenerated_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TimeGenerated);
      }
      if (messageCase_ == MessageOneofCase.ElementCreated) {
        output.WriteRawTag(18);
        output.WriteMessage(ElementCreated);
      }
      if (messageCase_ == MessageOneofCase.ElementDeleted) {
        output.WriteRawTag(26);
        output.WriteMessage(ElementDeleted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (timeGenerated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeGenerated);
      }
      if (messageCase_ == MessageOneofCase.ElementCreated) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementCreated);
      }
      if (messageCase_ == MessageOneofCase.ElementDeleted) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementDeleted);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.timeGenerated_ != null) {
        if (timeGenerated_ == null) {
          TimeGenerated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeGenerated.MergeFrom(other.TimeGenerated);
      }
      switch (other.MessageCase) {
        case MessageOneofCase.ElementCreated:
          if (ElementCreated == null) {
            ElementCreated = new global::Domain.Protos.Messages.ElementCreatedMessage();
          }
          ElementCreated.MergeFrom(other.ElementCreated);
          break;
        case MessageOneofCase.ElementDeleted:
          if (ElementDeleted == null) {
            ElementDeleted = new global::Domain.Protos.Messages.ElementDeletedMessage();
          }
          ElementDeleted.MergeFrom(other.ElementDeleted);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timeGenerated_ == null) {
              TimeGenerated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeGenerated);
            break;
          }
          case 18: {
            global::Domain.Protos.Messages.ElementCreatedMessage subBuilder = new global::Domain.Protos.Messages.ElementCreatedMessage();
            if (messageCase_ == MessageOneofCase.ElementCreated) {
              subBuilder.MergeFrom(ElementCreated);
            }
            input.ReadMessage(subBuilder);
            ElementCreated = subBuilder;
            break;
          }
          case 26: {
            global::Domain.Protos.Messages.ElementDeletedMessage subBuilder = new global::Domain.Protos.Messages.ElementDeletedMessage();
            if (messageCase_ == MessageOneofCase.ElementDeleted) {
              subBuilder.MergeFrom(ElementDeleted);
            }
            input.ReadMessage(subBuilder);
            ElementDeleted = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (timeGenerated_ == null) {
              TimeGenerated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeGenerated);
            break;
          }
          case 18: {
            global::Domain.Protos.Messages.ElementCreatedMessage subBuilder = new global::Domain.Protos.Messages.ElementCreatedMessage();
            if (messageCase_ == MessageOneofCase.ElementCreated) {
              subBuilder.MergeFrom(ElementCreated);
            }
            input.ReadMessage(subBuilder);
            ElementCreated = subBuilder;
            break;
          }
          case 26: {
            global::Domain.Protos.Messages.ElementDeletedMessage subBuilder = new global::Domain.Protos.Messages.ElementDeletedMessage();
            if (messageCase_ == MessageOneofCase.ElementDeleted) {
              subBuilder.MergeFrom(ElementDeleted);
            }
            input.ReadMessage(subBuilder);
            ElementDeleted = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
