// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: events/events.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Application.Protos.Events {

  /// <summary>Holder for reflection information generated from events/events.proto</summary>
  public static partial class EventsReflection {

    #region Descriptor
    /// <summary>File descriptor for events/events.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNldmVudHMvZXZlbnRzLnByb3RvEgZldmVudHMaH2dvb2dsZS9wcm90b2J1",
            "Zi90aW1lc3RhbXAucHJvdG8aM2V2ZW50cy9pbmtfc3Ryb2tlX2VsZW1lbnRf",
            "YWRkZWRfdG9fcGFnZV9ldmVudC5wcm90bxosZXZlbnRzL2VsZW1lbnRfcmVt",
            "b3ZlZF9mcm9tX3BhZ2VfZXZlbnQucHJvdG8iigIKBUV2ZW50Ei8KC29jY3Vy",
            "cmVkX2F0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIPCgdw",
            "YWdlX2lkGAIgASgJEhYKDnJlcGxpY2F0aW9uX2lkGAMgASgEElQKIGlua19z",
            "dHJva2VfZWxlbWVudF9hZGRlZF90b19wYWdlGAQgASgLMiguZXZlbnRzLklu",
            "a1N0cm9rZUVsZW1lbnRBZGRlZFRvUGFnZUV2ZW50SAASSAoZZWxlbWVudF9y",
            "ZW1vdmVkX2Zyb21fcGFnZRgFIAEoCzIjLmV2ZW50cy5FbGVtZW50UmVtb3Zl",
            "ZEZyb21QYWdlRXZlbnRIAEIHCgVldmVudCIrCgpFdmVudEdyb3VwEh0KBmV2",
            "ZW50cxgBIAMoCzINLmV2ZW50cy5FdmVudEIcqgIZQXBwbGljYXRpb24uUHJv",
            "dG9zLkV2ZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Application.Protos.Events.InkStrokeElementAddedToPageEventReflection.Descriptor, global::Application.Protos.Events.ElementRemovedFromPageEventReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Application.Protos.Events.Event), global::Application.Protos.Events.Event.Parser, new[]{ "OccurredAt", "PageId", "ReplicationId", "InkStrokeElementAddedToPage", "ElementRemovedFromPage" }, new[]{ "Event" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Application.Protos.Events.EventGroup), global::Application.Protos.Events.EventGroup.Parser, new[]{ "Events" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Base message definition
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Application.Protos.Events.EventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event(Event other) : this() {
      occurredAt_ = other.occurredAt_ != null ? other.occurredAt_.Clone() : null;
      pageId_ = other.pageId_;
      replicationId_ = other.replicationId_;
      switch (other.EventCase) {
        case EventOneofCase.InkStrokeElementAddedToPage:
          InkStrokeElementAddedToPage = other.InkStrokeElementAddedToPage.Clone();
          break;
        case EventOneofCase.ElementRemovedFromPage:
          ElementRemovedFromPage = other.ElementRemovedFromPage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "occurred_at" field.</summary>
    public const int OccurredAtFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp occurredAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp OccurredAt {
      get { return occurredAt_; }
      set {
        occurredAt_ = value;
      }
    }

    /// <summary>Field number for the "page_id" field.</summary>
    public const int PageIdFieldNumber = 2;
    private string pageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PageId {
      get { return pageId_; }
      set {
        pageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "replication_id" field.</summary>
    public const int ReplicationIdFieldNumber = 3;
    private ulong replicationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ReplicationId {
      get { return replicationId_; }
      set {
        replicationId_ = value;
      }
    }

    /// <summary>Field number for the "ink_stroke_element_added_to_page" field.</summary>
    public const int InkStrokeElementAddedToPageFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Application.Protos.Events.InkStrokeElementAddedToPageEvent InkStrokeElementAddedToPage {
      get { return eventCase_ == EventOneofCase.InkStrokeElementAddedToPage ? (global::Application.Protos.Events.InkStrokeElementAddedToPageEvent) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.InkStrokeElementAddedToPage;
      }
    }

    /// <summary>Field number for the "element_removed_from_page" field.</summary>
    public const int ElementRemovedFromPageFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Application.Protos.Events.ElementRemovedFromPageEvent ElementRemovedFromPage {
      get { return eventCase_ == EventOneofCase.ElementRemovedFromPage ? (global::Application.Protos.Events.ElementRemovedFromPageEvent) event_ : null; }
      set {
        event_ = value;
        eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.ElementRemovedFromPage;
      }
    }

    private object event_;
    /// <summary>Enum of possible cases for the "event" oneof.</summary>
    public enum EventOneofCase {
      None = 0,
      InkStrokeElementAddedToPage = 4,
      ElementRemovedFromPage = 5,
    }
    private EventOneofCase eventCase_ = EventOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventOneofCase EventCase {
      get { return eventCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEvent() {
      eventCase_ = EventOneofCase.None;
      event_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OccurredAt, other.OccurredAt)) return false;
      if (PageId != other.PageId) return false;
      if (ReplicationId != other.ReplicationId) return false;
      if (!object.Equals(InkStrokeElementAddedToPage, other.InkStrokeElementAddedToPage)) return false;
      if (!object.Equals(ElementRemovedFromPage, other.ElementRemovedFromPage)) return false;
      if (EventCase != other.EventCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (occurredAt_ != null) hash ^= OccurredAt.GetHashCode();
      if (PageId.Length != 0) hash ^= PageId.GetHashCode();
      if (ReplicationId != 0UL) hash ^= ReplicationId.GetHashCode();
      if (eventCase_ == EventOneofCase.InkStrokeElementAddedToPage) hash ^= InkStrokeElementAddedToPage.GetHashCode();
      if (eventCase_ == EventOneofCase.ElementRemovedFromPage) hash ^= ElementRemovedFromPage.GetHashCode();
      hash ^= (int) eventCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (occurredAt_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OccurredAt);
      }
      if (PageId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PageId);
      }
      if (ReplicationId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(ReplicationId);
      }
      if (eventCase_ == EventOneofCase.InkStrokeElementAddedToPage) {
        output.WriteRawTag(34);
        output.WriteMessage(InkStrokeElementAddedToPage);
      }
      if (eventCase_ == EventOneofCase.ElementRemovedFromPage) {
        output.WriteRawTag(42);
        output.WriteMessage(ElementRemovedFromPage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (occurredAt_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OccurredAt);
      }
      if (PageId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PageId);
      }
      if (ReplicationId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(ReplicationId);
      }
      if (eventCase_ == EventOneofCase.InkStrokeElementAddedToPage) {
        output.WriteRawTag(34);
        output.WriteMessage(InkStrokeElementAddedToPage);
      }
      if (eventCase_ == EventOneofCase.ElementRemovedFromPage) {
        output.WriteRawTag(42);
        output.WriteMessage(ElementRemovedFromPage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (occurredAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OccurredAt);
      }
      if (PageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PageId);
      }
      if (ReplicationId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ReplicationId);
      }
      if (eventCase_ == EventOneofCase.InkStrokeElementAddedToPage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InkStrokeElementAddedToPage);
      }
      if (eventCase_ == EventOneofCase.ElementRemovedFromPage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementRemovedFromPage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      if (other.occurredAt_ != null) {
        if (occurredAt_ == null) {
          OccurredAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        OccurredAt.MergeFrom(other.OccurredAt);
      }
      if (other.PageId.Length != 0) {
        PageId = other.PageId;
      }
      if (other.ReplicationId != 0UL) {
        ReplicationId = other.ReplicationId;
      }
      switch (other.EventCase) {
        case EventOneofCase.InkStrokeElementAddedToPage:
          if (InkStrokeElementAddedToPage == null) {
            InkStrokeElementAddedToPage = new global::Application.Protos.Events.InkStrokeElementAddedToPageEvent();
          }
          InkStrokeElementAddedToPage.MergeFrom(other.InkStrokeElementAddedToPage);
          break;
        case EventOneofCase.ElementRemovedFromPage:
          if (ElementRemovedFromPage == null) {
            ElementRemovedFromPage = new global::Application.Protos.Events.ElementRemovedFromPageEvent();
          }
          ElementRemovedFromPage.MergeFrom(other.ElementRemovedFromPage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (occurredAt_ == null) {
              OccurredAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OccurredAt);
            break;
          }
          case 18: {
            PageId = input.ReadString();
            break;
          }
          case 24: {
            ReplicationId = input.ReadUInt64();
            break;
          }
          case 34: {
            global::Application.Protos.Events.InkStrokeElementAddedToPageEvent subBuilder = new global::Application.Protos.Events.InkStrokeElementAddedToPageEvent();
            if (eventCase_ == EventOneofCase.InkStrokeElementAddedToPage) {
              subBuilder.MergeFrom(InkStrokeElementAddedToPage);
            }
            input.ReadMessage(subBuilder);
            InkStrokeElementAddedToPage = subBuilder;
            break;
          }
          case 42: {
            global::Application.Protos.Events.ElementRemovedFromPageEvent subBuilder = new global::Application.Protos.Events.ElementRemovedFromPageEvent();
            if (eventCase_ == EventOneofCase.ElementRemovedFromPage) {
              subBuilder.MergeFrom(ElementRemovedFromPage);
            }
            input.ReadMessage(subBuilder);
            ElementRemovedFromPage = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (occurredAt_ == null) {
              OccurredAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OccurredAt);
            break;
          }
          case 18: {
            PageId = input.ReadString();
            break;
          }
          case 24: {
            ReplicationId = input.ReadUInt64();
            break;
          }
          case 34: {
            global::Application.Protos.Events.InkStrokeElementAddedToPageEvent subBuilder = new global::Application.Protos.Events.InkStrokeElementAddedToPageEvent();
            if (eventCase_ == EventOneofCase.InkStrokeElementAddedToPage) {
              subBuilder.MergeFrom(InkStrokeElementAddedToPage);
            }
            input.ReadMessage(subBuilder);
            InkStrokeElementAddedToPage = subBuilder;
            break;
          }
          case 42: {
            global::Application.Protos.Events.ElementRemovedFromPageEvent subBuilder = new global::Application.Protos.Events.ElementRemovedFromPageEvent();
            if (eventCase_ == EventOneofCase.ElementRemovedFromPage) {
              subBuilder.MergeFrom(ElementRemovedFromPage);
            }
            input.ReadMessage(subBuilder);
            ElementRemovedFromPage = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventGroup : pb::IMessage<EventGroup>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventGroup> _parser = new pb::MessageParser<EventGroup>(() => new EventGroup());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventGroup> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Application.Protos.Events.EventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventGroup() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventGroup(EventGroup other) : this() {
      events_ = other.events_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventGroup Clone() {
      return new EventGroup(this);
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Application.Protos.Events.Event> _repeated_events_codec
        = pb::FieldCodec.ForMessage(10, global::Application.Protos.Events.Event.Parser);
    private readonly pbc::RepeatedField<global::Application.Protos.Events.Event> events_ = new pbc::RepeatedField<global::Application.Protos.Events.Event>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Application.Protos.Events.Event> Events {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventGroup);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventGroup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!events_.Equals(other.events_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= events_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      events_.WriteTo(output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      events_.WriteTo(ref output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += events_.CalculateSize(_repeated_events_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventGroup other) {
      if (other == null) {
        return;
      }
      events_.Add(other.events_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            events_.AddEntriesFrom(ref input, _repeated_events_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
