// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: elements/element.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Application.Protos.Elements {

  /// <summary>Holder for reflection information generated from elements/element.proto</summary>
  public static partial class ElementReflection {

    #region Descriptor
    /// <summary>File descriptor for elements/element.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ElementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZlbGVtZW50cy9lbGVtZW50LnByb3RvEghlbGVtZW50cxofZ29vZ2xlL3By",
            "b3RvYnVmL3RpbWVzdGFtcC5wcm90bxohZWxlbWVudHMvaW5rX3N0cm9rZV9l",
            "bGVtZW50LnByb3RvIoUBCgdFbGVtZW50EgoKAmlkGAEgASgJEjEKDWNyZWF0",
            "aW9uX2RhdGUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAK",
            "Cmlua19zdHJva2UYAyABKAsyGi5lbGVtZW50cy5JbmtTdHJva2VFbGVtZW50",
            "SABCCQoHZWxlbWVudEIeqgIbQXBwbGljYXRpb24uUHJvdG9zLkVsZW1lbnRz",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Application.Protos.Elements.InkStrokeElementReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Application.Protos.Elements.Element), global::Application.Protos.Elements.Element.Parser, new[]{ "Id", "CreationDate", "InkStroke" }, new[]{ "Element" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Base message definition
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Element : pb::IMessage<Element>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Element> _parser = new pb::MessageParser<Element>(() => new Element());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Element> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Application.Protos.Elements.ElementReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element(Element other) : this() {
      id_ = other.id_;
      creationDate_ = other.creationDate_ != null ? other.creationDate_.Clone() : null;
      switch (other.ElementCase) {
        case ElementOneofCase.InkStroke:
          InkStroke = other.InkStroke.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element Clone() {
      return new Element(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creation_date" field.</summary>
    public const int CreationDateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp creationDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreationDate {
      get { return creationDate_; }
      set {
        creationDate_ = value;
      }
    }

    /// <summary>Field number for the "ink_stroke" field.</summary>
    public const int InkStrokeFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Application.Protos.Elements.InkStrokeElement InkStroke {
      get { return elementCase_ == ElementOneofCase.InkStroke ? (global::Application.Protos.Elements.InkStrokeElement) element_ : null; }
      set {
        element_ = value;
        elementCase_ = value == null ? ElementOneofCase.None : ElementOneofCase.InkStroke;
      }
    }

    private object element_;
    /// <summary>Enum of possible cases for the "element" oneof.</summary>
    public enum ElementOneofCase {
      None = 0,
      InkStroke = 3,
    }
    private ElementOneofCase elementCase_ = ElementOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ElementOneofCase ElementCase {
      get { return elementCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearElement() {
      elementCase_ = ElementOneofCase.None;
      element_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Element);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Element other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(CreationDate, other.CreationDate)) return false;
      if (!object.Equals(InkStroke, other.InkStroke)) return false;
      if (ElementCase != other.ElementCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (creationDate_ != null) hash ^= CreationDate.GetHashCode();
      if (elementCase_ == ElementOneofCase.InkStroke) hash ^= InkStroke.GetHashCode();
      hash ^= (int) elementCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (creationDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreationDate);
      }
      if (elementCase_ == ElementOneofCase.InkStroke) {
        output.WriteRawTag(26);
        output.WriteMessage(InkStroke);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (creationDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreationDate);
      }
      if (elementCase_ == ElementOneofCase.InkStroke) {
        output.WriteRawTag(26);
        output.WriteMessage(InkStroke);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (creationDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreationDate);
      }
      if (elementCase_ == ElementOneofCase.InkStroke) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InkStroke);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Element other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.creationDate_ != null) {
        if (creationDate_ == null) {
          CreationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreationDate.MergeFrom(other.CreationDate);
      }
      switch (other.ElementCase) {
        case ElementOneofCase.InkStroke:
          if (InkStroke == null) {
            InkStroke = new global::Application.Protos.Elements.InkStrokeElement();
          }
          InkStroke.MergeFrom(other.InkStroke);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (creationDate_ == null) {
              CreationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreationDate);
            break;
          }
          case 26: {
            global::Application.Protos.Elements.InkStrokeElement subBuilder = new global::Application.Protos.Elements.InkStrokeElement();
            if (elementCase_ == ElementOneofCase.InkStroke) {
              subBuilder.MergeFrom(InkStroke);
            }
            input.ReadMessage(subBuilder);
            InkStroke = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (creationDate_ == null) {
              CreationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreationDate);
            break;
          }
          case 26: {
            global::Application.Protos.Elements.InkStrokeElement subBuilder = new global::Application.Protos.Elements.InkStrokeElement();
            if (elementCase_ == ElementOneofCase.InkStroke) {
              subBuilder.MergeFrom(InkStroke);
            }
            input.ReadMessage(subBuilder);
            InkStroke = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
